# Generated by Django 5.1.7 on 2025-04-07 23:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="availcheck",
            name="updated_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2025, 4, 7, 23, 20, 28, 617210, tzinfo=datetime.timezone.utc
                )
            ),
            preserve_default=False,
        ),
    ]
