# Generated by Django 5.1.7 on 2025-03-10 01:32

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="birthday",
            field=models.DateField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(
                        datetime.date(1900, 1, 1), "No birthdays before 1900"
                    ),
                    django.core.validators.MaxValueValidator(
                        datetime.date(2025, 3, 10), "No future birthdays"
                    ),
                ],
                verbose_name="Date of birth",
            ),
        ),
    ]
