# Generated by Django 5.1.7 on 2025-04-07 23:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0002_availcheck_updated_at"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="availability",
            name="updated_at",
        ),
    ]
